apiVersion: apps/v1
kind: Deployment
metadata:
  name: aptits-deployment
  labels:
    app: aptits
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aptits
  template:
    metadata:
      labels:
        app: aptits
    spec:
      containers:
      - name: aptits-container
        image: vamshidhar1128/meesho
        ports:
        - containerPort: 8081
